version: '3.9'

services:
  # todo: muzz

  # todo: redis

  db:
    image: mariadb:10.9-jammy
    restart: always
    environment:
      MARIADB_NAME: $MUZZ_DB_NAME
      MARIADB_USER: $MUZZ_DB_USER
      MARIADB_PASSWORD: $MUZZ_DB_PASSWORD
      MARIADB_ROOT_PASSWORD: $MUZZ_DB_ROOT_PASSWORD
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
