version: '3.9'

services:
  # todo: muzz

  kv:
    image: redis:7.0-bullseye
    ports:
      - "$MUZZ_DEV_KV_PORT:6379"
    volumes:
      - kv-data:/data

  db:
    image: mariadb:10.9-jammy
    restart: always
    environment:
      MARIADB_NAME: $MUZZ_DB_NAME
      MARIADB_USER: $MUZZ_DB_USER
      MARIADB_PASSWORD: $MUZZ_DB_PASSWORD
      MARIADB_ROOT_PASSWORD: $MUZZ_DB_ROOT_PASSWORD
    ports:
      - "$MUZZ_DEV_DB_PORT:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  kv-data:
